//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOform.Preventive_Maintenance__PM__Report_BB2._4
{


    public partial class WebForm1
    {
    }
}
