//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class USOEntities : DbContext
    {
        public USOEntities()
            : base("name=USOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AnswerType> AnswerTypes { get; set; }
        public virtual DbSet<Head> Heads { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<TBAnswer_Type> TBAnswer_Type { get; set; }
        public virtual DbSet<TBSurvey_answer01> TBSurvey_answer01 { get; set; }
        public virtual DbSet<TBSurvey_Head> TBSurvey_Head { get; set; }
        public virtual DbSet<TBSurvey_Question> TBSurvey_Question { get; set; }
        public virtual DbSet<TBSurvey_Section> TBSurvey_Section { get; set; }
    }
}
