//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSurvey_answer01
    {
        public int TID { get; set; }
        public Nullable<int> HID { get; set; }
        public Nullable<int> SID { get; set; }
        public Nullable<int> QID { get; set; }
        public Nullable<int> AnsType { get; set; }
        public string AnsDes { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
